module.exports = {
  appId: 'com.yuantu.agent',
  productName: 'YuanTu Agent',
  extraMetadata: { main: 'dist/desktop/main.cjs' },
  directories: { output: 'dist/release', buildResources: 'build' },
  icon: 'build/icon.png',
  asar: false,
  npmRebuild: false,
  // Package only compiled code, excluding release artifacts and unpacked apps.
  files: [
    'dist/apps/**/*',
    'dist/desktop/**/*',
    'dist/packages/**/*',
    'dist/program-runner/**/*',
    'package.json',
    'LICENSE',
    '!dist/**/*.map',
    '!dist/**/*.d.ts',
  ],
  extraResources: [{ from: '.scratch/packaging/runtime', to: 'runtime' }],
  win: {
    target: [{ target: 'nsis', arch: ['x64'] }],
    icon: 'build/icon.ico',
    signExecutable: false,
  },
  nsis: {
    installerIcon: 'build/icon.ico',
    uninstallerIcon: 'build/icon.ico',
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    deleteAppDataOnUninstall: false,
    createDesktopShortcut: false,
    createStartMenuShortcut: true,
    artifactName: 'YuanTu-Agent-${version}-windows-${arch}-setup.${ext}',
  },
};
